#!/bin/bash

# MemeFlow Social Platform - Supabase Migration Script
# Este script ajuda a executar as migrações do banco de dados

echo "🚀 MemeFlow Social Platform - Database Setup"
echo "=============================================="
echo ""
echo "Este script NÃO executa SQL automaticamente."
echo "Você precisa fazer isso manualmente no Supabase Dashboard."
echo ""
echo "📋 Passo 1: Criar projeto Supabase"
echo "   1. Acesse https://supabase.com"
echo "   2. Clique em 'New Project'"
echo "   3. Preencha com seus dados"
echo "   4. Aguarde a criação (pode levar alguns minutos)"
echo ""
echo "🔑 Passo 2: Obter credenciais"
echo "   1. Vá para Settings → API"
echo "   2. Copie o URL do projeto (Project URL)"
echo "   3. Copie a chave anon (anon public)"
echo "   4. Salve em um lugar seguro"
echo ""
echo "⚙️  Passo 3: Configurar variáveis de ambiente"
echo "   1. Crie um arquivo .env na raiz do projeto"
echo "   2. Adicione:"
echo "      VITE_SUPABASE_URL=<seu-project-url>"
echo "      VITE_SUPABASE_ANON_KEY=<sua-anon-key>"
echo ""
echo "🔗 Passo 4: Executar SQL Schema"
echo "   1. No Supabase Dashboard, vá para: SQL Editor"
echo "   2. Clique em 'New query'"
echo "   3. Abra o arquivo: supabase/schema.sql"
echo "   4. Copie TODO o conteúdo"
echo "   5. Cole no SQL Editor do Supabase"
echo "   6. Clique em 'Run' (Ctrl+Enter ou ⌘+Enter)"
echo "   7. Aguarde a execução (deve levar ~30 segundos)"
echo ""
echo "✅ Passo 5: Verificar instalação"
echo "   1. Abra o navegador e vá para sua app"
echo "   2. Abra o console (F12)"
echo "   3. Execute:"
echo "      const { data } = await supabase.from('profiles').select('count()')"
echo "      console.log(data)"
echo "   4. Se retornar um número, está funcionando! ✨"
echo ""
echo "📁 Arquivos importantes:"
echo "   - supabase/schema.sql      → SQL completo para executar"
echo "   - supabase/config.ts       → Configurações centralizadas"
echo "   - supabase/README.md       → Documentação detalhada"
echo "   - src/lib/supabase.ts      → Cliente Supabase"
echo "   - src/lib/supabaseHelpers.ts → Funções helper prontas"
echo "   - src/types/database.ts    → Types TypeScript"
echo "   - .env.example             → Template de env"
echo ""
echo "❓ Dúvidas?"
echo "   Consulte supabase/README.md ou SUPABASE_SETUP.md"
echo ""
